Repository WuraLab/Boardly, pull requests merged in 2021-03, with the labels that each got.

#30 Database Models and Automigration
  .env
  .github/workflows/goTest.yml
  .gitignore
  .test.env
  Dockerfile
  docker-compose.yaml
  go.mod
  go.sum
  src/backend/cmd/boardly.go
  src/backend/internal/config/config.go
  src/backend/internal/controllers/controller.go
  src/backend/internal/db/migrations.go
  src/backend/internal/db/migrations_test.go
  src/backend/internal/middlewares/middleware.go
  src/backend/internal/models/models.go
  src/backend/internal/models/models_test.go
  src/backend/internal/models/roles.go
  src/backend/internal/models/roles_test.go
  src/backend/internal/models/users.go
  src/backend/internal/models/users_test.go
  src/backend/internal/routes/routes.go
  src/backend/main.go
  src/backend/pkg/api/api.go
Labels: area/backend, area/database, review

#45 Setup project structure and modules
  src/web/.eslintignore
  src/web/.eslintrc.js
  src/web/.prettierignore
  src/web/.prettierrc
  src/web/.prettierrc.js
  src/web/components/forgotpassword/ForgotPassword.tsx
  src/web/components/login/Login.tsx
  src/web/components/signup/SignUp.tsx
  src/web/pages/auth/forgot-password-view.tsx
  src/web/pages/auth/login-view.tsx
  src/web/pages/auth/sign-up-view.tsx
  src/web/pages/index.tsx
Labels: area/frontend

#43 WIP #BRD-19 Password Recovery UI
  src/web/components/forgotpassword/ForgotPassword.tsx
  src/web/components/login/Login.tsx
  src/web/components/signup/SignUp.tsx
  src/web/pages/auth/forgot-password-view.tsx
  src/web/pages/auth/login-view.tsx
  src/web/pages/auth/sign-up-view.tsx
  src/web/pages/index.tsx
Labels: area/frontend

#46 Forgotpassword UI
  .vscode/settings.json
  package-lock.json
  package.json
  src/web/assets/global-styles.tsx
  src/web/components/forgotpassword/ForgotPassword.tsx
  src/web/next.config.js
  src/web/pages/auth/forgot-password-view.tsx
  src/web/public/Group5.png
  src/web/public/Group5.svg
  src/web/public/forgot_password.svg
  src/web/public/forgot_password1.svg
  src/web/public/forgot_password2.svg
  src/web/public/logo.svg
  src/web/tsconfig.json
Labels: area/frontend

#53 WIP BRD-49 || reset password UI
  .gitignore
  package-lock.json
  src/web/assets/global-styles.tsx
  src/web/components/resetpassword/ResetPassword.tsx
  src/web/pages/_app.tsx
  src/web/pages/auth/forgot-password.tsx
  src/web/pages/auth/login-view.tsx
  src/web/pages/auth/reset-password.tsx
  src/web/pages/index.tsx
  src/web/public/recover-password.svg
  src/web/theme.js
  yarn.lock
Labels: area/frontend

#54 Add JWT Auth
  .env
  .test.env
  go.mod
  go.sum
  src/backend/cmd/boardly.go
  src/backend/internal/config/config.go
  src/backend/internal/controllers/user.go
  src/backend/internal/controllers/user_test.go
  src/backend/internal/errors/error.go
  src/backend/internal/middlewares/jwt.go
  src/backend/internal/models/user.go
  src/backend/internal/routes/routes.go
Labels: area/backend, review
