Repository WuraLab/Boardly, pull requests merged in 2021-02, with the labels that each got.

#16 CI: Prevent Merging on WIP
  .github/mergeable.yml
Labels: area/developer

#22 Project Structure
  src/backend/common/common.go
  src/backend/main.go
  src/web/components/index.ts
  src/web/lib/index.ts
  src/web/pages/index.tsx
  src/web/public/favicon.ico
Labels: area/developer

#38 Created GHA for test coverage
  .github/workflows/goTest.yml
  .gitignore
  README.md
  src/backend/common/common.go
  src/backend/main.go
Labels: area/developer, review, test

#37 #35 || fix entry point of nextjs app
  package-lock.json
  package.json
  src/web/next-env.d.ts
  src/web/tsconfig.json
Labels: area/frontend, bug

#36 WIP: #19 password recovery ui
  .idea/workspace.xml
  package.json
  src/web/next-env.d.ts
  src/web/tsconfig.json
Labels: area/frontend
